export const SEARCH_FOUCS = 'SEARCH_FOUCS';
export const SEARCH_BLUR = 'SEARCH_BLUR';
export const CHANGE_HOTLIST = 'CHANGE_HOTLIST';
export const MOUSEENTER = 'MOUSEENTER';
export const MOUSELEAVE = 'MOUSELEAVE';
export const CHNAGEPAGE = 'CHNAGEPAGE';